#!/bin/bash
# Change localhost IP address to 127.0.0.2
sudo sed -i 's/127\.0\.0\.1/127.0.0.2/' /etc/hosts

# Change facebook.com IP address to 8.8.8.8
sudo sed -i 's/\(facebook\.com\)\(.*\)/8.8.8.8\t\1\2/' /etc/hosts
